export const mockActivity = [
  { id: 'a-1', message: 'Mission "Alpha Core" completed successfully.', time: '2m ago' },
  { id: 'a-2', message: 'New API Key generated by Admin.', time: '1hr ago' },
  { id: 'a-3', message: 'Workflow "Data Scrape" updated.', time: '3hrs ago' }
];
