from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# 1. Enums
class AgentRole(str, Enum):
    ARCHITECT = "architect"
    PLANNER = "planner"
    BACKEND_ENGINEER = "backend_engineer"
    FRONTEND_ENGINEER = "frontend_engineer"
    REVIEWER = "reviewer"
    SECURITY_ENGINEER = "security_engineer"
    OPTIMIZER = "optimizer"
    DEPLOYMENT_ENGINEER = "deployment_engineer"


class RecoveryAction(str, Enum):
    RETRY = "retry"
    ALTERNATIVE_WORKER = "alternative_worker"
    ALTERNATIVE_PROVIDER = "alternative_provider"
    ALTERNATIVE_MODEL = "alternative_model"
    ALTERNATIVE_WORKFLOW = "alternative_workflow"
    ALTERNATIVE_ARCHITECTURE = "alternative_architecture"
    ESCALATION = "escalation"
    ABORT = "abort"


# 2. Goal Hierarchy
class Goal(BaseModel):
    """
    Highest-level planning object in OrchX. Immutable once accepted.
    """
    goal_id: str
    title: str
    description: str
    objectives: List[str] = Field(default_factory=list)
    milestones: List[str] = Field(default_factory=list)
    capabilities_required: List[str] = Field(default_factory=list)
    status: str = Field("pending", description="pending, running, completed, failed")
    version: str = Field("1.0.0", description="Semantic version of this goal spec")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# 3. Architecture Council & Scoring
class ArchitectureCandidate(BaseModel):
    """
    Design proposal generated by the ArchitectureCouncil.
    """
    architecture_id: str
    title: str
    summary: str
    technology_stack: List[str] = Field(default_factory=list)
    folder_structure: Dict[str, Any] = Field(default_factory=dict)
    service_boundaries: List[str] = Field(default_factory=list)
    deployment_strategy: str
    scalability_considerations: str
    security_considerations: str
    estimated_complexity: str = Field("medium", description="low/medium/high")
    assumptions: List[str] = Field(default_factory=list)


class ArchitectureScore(BaseModel):
    """
    Normalized scores evaluated over design candidates.
    """
    maintainability: float = 0.0
    scalability: float = 0.0
    performance: float = 0.0
    security: float = 0.0
    reliability: float = 0.0
    cost: float = 0.0
    complexity: float = 0.0
    overall_score: float = 0.0


class ArchitectureDecisionReport(BaseModel):
    """
    Immutable decision report produced by the DecisionEngine.
    """
    report_id: str
    selected_candidate_id: str
    ranking: List[str] = Field(default_factory=list, description="Ordered candidate IDs")
    confidence: float = Field(..., description="Decision confidence from 0.0 to 1.0")
    reasoning: str = Field(..., description="Explainable analysis detailing why candidate was selected")
    weighted_scores: Dict[str, ArchitectureScore] = Field(default_factory=dict)
    tradeoffs: Dict[str, str] = Field(default_factory=dict)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# 4. Reflection & Recovery
class ReflectionReport(BaseModel):
    """
    Lessons learned report generated upon Goal execution completion.
    """
    report_id: str
    goal_id: str
    objectives_achieved: List[str] = Field(default_factory=list)
    failures_encountered: List[str] = Field(default_factory=list)
    bottlenecks: List[str] = Field(default_factory=list)
    lessons_learned: List[str] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class RecoveryPlan(BaseModel):
    """
    Advisory remediation plan triggered upon execution faults.
    """
    plan_id: str
    execution_id: str
    suggested_action: RecoveryAction
    reason: str
    approved: bool = Field(False, description="Requires user validation approval")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
