from abc import ABC, abstractmethod
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from orchx_core.interfaces.task import Task, ResourceRequirements, TaskState
from orchx_core.interfaces.worker import Worker, WorkerLease


class ExecutionContext(BaseModel):
    """
    Structured context payload containing all execution parameters required by sandboxes.
    Remains immutable during the run sequence.
    """
    execution_id: str = Field(..., description="Unique execution UUID")
    task: Task = Field(..., description="Target Task specification contract")
    worker: Worker = Field(..., description="Target Worker metadata")
    lease: WorkerLease = Field(..., description="Target WorkerLease reservation")
    env_vars: Dict[str, str] = Field(default_factory=dict, description="Custom shell environment settings")
    working_directory: str = Field("/tmp", description="Isolated workspace path directory")
    resource_limits: ResourceRequirements = Field(default_factory=ResourceRequirements)


class SandboxResult(BaseModel):
    """
    Standardized execution output generated by any Sandbox isolation runner.
    """
    execution_id: str
    exit_code: int = Field(0, description="Process return code. 0 represents success")
    stdout: str = Field("", description="Standard output log stream")
    stderr: str = Field("", description="Standard error log stream")
    execution_duration: float = Field(0.0, description="Run duration in seconds")
    cpu_time: float = Field(0.0, description="Total CPU processing seconds consumed")
    memory_usage: int = Field(0, description="Max RAM memory bytes utilized")
    produced_artifacts: List[str] = Field(default_factory=list, description="IDs of generated output artifacts")
    emitted_events: List[Dict[str, Any]] = Field(default_factory=list, description="Event records dispatched during run")


class ExecutionReport(BaseModel):
    """
    Immutable historical audit summary documenting a completed Task execution.
    """
    execution_id: str
    task_id: str
    worker_id: str
    sandbox_type: str = Field(..., description="Sandbox identifier, e.g. 'local_process', 'docker'")
    started_at: datetime
    finished_at: datetime
    duration: float
    final_status: TaskState
    produced_artifacts: List[str] = Field(default_factory=list)
    execution_metrics: Dict[str, Any] = Field(default_factory=dict)
    logs_reference: Optional[str] = Field(None, description="Diagnostic logs URL or path link")


class Sandbox(ABC):
    """
    Abstract interface for executing tasks inside isolated environments.
    """

    @abstractmethod
    async def execute(self, context: ExecutionContext) -> SandboxResult:
        """
        Runs task commands in the isolated environment and returns standard SandboxResult.
        """
        pass
